require:
  - ts-node/register
  - test/hooks.cjs
parallel: true
extension: [ts]
check-leaks: true
global:
  - indexedDB
  - IDBCursor
  - IDBCursorWithValue
  - IDBDatabase
  - IDBFactory
  - IDBIndex
  - IDBKeyRange
  - IDBObjectStore
  - IDBOpenDBRequest
  - IDBRequest
  - IDBTransaction
  - IDBVersionChangeEvent
